window.DASHBOARD_DATA = {
  sites: [
    {
      id: "andina-norte",
      name: "Faena Andina Norte",
      region: "Region de Antofagasta",
      operation: "Rajo abierto y chancado primario",
      contractor: "Contrato Mina 24-36",
      workers: 184,
      risk: "Alto",
    },
    {
      id: "salar-poniente",
      name: "Faena Salar Poniente",
      region: "Region de Atacama",
      operation: "Planta de procesamiento y piscinas",
      contractor: "Contrato Planta 18-30",
      workers: 96,
      risk: "Medio",
    },
    {
      id: "cordillera-sur",
      name: "Faena Cordillera Sur",
      region: "Region de Coquimbo",
      operation: "Tuneles, ventilacion y desarrollo",
      contractor: "Contrato Subterranea 31-44",
      workers: 132,
      risk: "Alto",
    },
    {
      id: "puerto-minero",
      name: "Terminal Puerto Minero",
      region: "Region de Valparaiso",
      operation: "Acopio, correas y embarque",
      contractor: "Contrato Logistica 07-19",
      workers: 74,
      risk: "Medio",
    },
  ],
  records: [
    {
      siteId: "andina-norte",
      category: "Cursos",
      item: "Induccion hombre nuevo y obligacion de informar",
      owner: "RRHH Operaciones",
      dueDate: "2026-08-12",
      status: "Al dia",
      compliance: 96,
    },
    {
      siteId: "andina-norte",
      category: "Cursos",
      item: "Bloqueo y etiquetado LOTO",
      owner: "Mantenimiento Mina",
      dueDate: "2026-06-21",
      status: "Por vencer",
      compliance: 78,
    },
    {
      siteId: "andina-norte",
      category: "Documentacion",
      item: "MIPER actualizada por proceso critico",
      owner: "Prevencion Faena",
      dueDate: "2026-06-05",
      status: "Critico",
      compliance: 52,
    },
    {
      siteId: "andina-norte",
      category: "Acciones",
      item: "Cierre de hallazgo: protecciones de correa CV-04",
      owner: "Jefe Chancado",
      dueDate: "2026-06-10",
      status: "Critico",
      compliance: 35,
    },
    {
      siteId: "andina-norte",
      category: "Documentacion",
      item: "Plan de emergencia y simulacro mina",
      owner: "Administrador Contrato",
      dueDate: "2026-07-18",
      status: "Al dia",
      compliance: 90,
    },
    {
      siteId: "salar-poniente",
      category: "Cursos",
      item: "Manejo seguro de sustancias peligrosas",
      owner: "Jefe Planta",
      dueDate: "2026-07-04",
      status: "Al dia",
      compliance: 92,
    },
    {
      siteId: "salar-poniente",
      category: "Documentacion",
      item: "Hojas de datos de seguridad SDS vigentes",
      owner: "Bodega Quimicos",
      dueDate: "2026-06-16",
      status: "Por vencer",
      compliance: 81,
    },
    {
      siteId: "salar-poniente",
      category: "Acciones",
      item: "Regularizar duchas y lavaojos sector reactivos",
      owner: "Servicios Generales",
      dueDate: "2026-06-03",
      status: "Vencido",
      compliance: 44,
    },
    {
      siteId: "salar-poniente",
      category: "Documentacion",
      item: "Reglamento interno de orden, higiene y seguridad",
      owner: "Relaciones Laborales",
      dueDate: "2026-09-30",
      status: "Al dia",
      compliance: 95,
    },
    {
      siteId: "cordillera-sur",
      category: "Cursos",
      item: "Trabajo en altura fisica",
      owner: "Supervision Desarrollo",
      dueDate: "2026-05-24",
      status: "Vencido",
      compliance: 64,
    },
    {
      siteId: "cordillera-sur",
      category: "Cursos",
      item: "Espacios confinados y rescate inicial",
      owner: "Brigada Emergencia",
      dueDate: "2026-06-27",
      status: "Por vencer",
      compliance: 72,
    },
    {
      siteId: "cordillera-sur",
      category: "Documentacion",
      item: "Programa de ventilacion y medicion de gases",
      owner: "Ingenieria Mina",
      dueDate: "2026-06-08",
      status: "Critico",
      compliance: 48,
    },
    {
      siteId: "cordillera-sur",
      category: "Acciones",
      item: "Actualizar mapa de riesgos nivel 325",
      owner: "Prevencion Faena",
      dueDate: "2026-06-15",
      status: "Por vencer",
      compliance: 76,
    },
    {
      siteId: "puerto-minero",
      category: "Cursos",
      item: "Operacion segura de correas transportadoras",
      owner: "Jefe Turno Puerto",
      dueDate: "2026-08-02",
      status: "Al dia",
      compliance: 88,
    },
    {
      siteId: "puerto-minero",
      category: "Documentacion",
      item: "Acta Comite Paritario y plan mensual",
      owner: "Comite Paritario",
      dueDate: "2026-06-11",
      status: "Por vencer",
      compliance: 79,
    },
    {
      siteId: "puerto-minero",
      category: "Acciones",
      item: "Control de polvo en zona de acopio",
      owner: "Medio Ambiente y SST",
      dueDate: "2026-07-22",
      status: "Al dia",
      compliance: 86,
    },
  ],
};
